# Generated by Django 3.1.1 on 2020-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201119_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='total',
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
