# Generated by Django 3.2.10 on 2021-12-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201120_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaniports',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'adaniports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asianpaint',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asianpaint',
            },
        ),
        migrations.CreateModel(
            name='Axisbank',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'axisbank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bajajfinsv',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bajajfinsv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bajfinance',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bajfinance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bhartiartl',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bhartiartl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bpcl',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bpcl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Britannia',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'britannia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cipla',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cipla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coalindia',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coalindia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drreddy',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'drreddy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eichermot',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eichermot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gail',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grasim',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grasim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hcltech',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hcltech',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hdfc',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hdfc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hdfcbank',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hdfcbank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Heromotoco',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'heromotoco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hindalco',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hindalco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hindunilvr',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hindunilvr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Icicibank',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'icicibank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Indusindbk',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indusindbk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infratel',
            fields=[
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('date', models.TextField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'infratel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infy',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'infy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ioc',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ioc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itc',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'itc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jswsteel',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jswsteel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kotakbank',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kotakbank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lt',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maruti',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maruti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'm&m',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nestleind',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nestleind',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ntpc',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ntpc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ongc',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ongc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Powergrid',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'powergrid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reliance',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reliance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sbin',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sbin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shreecem',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shreecem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sunpharma',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sunpharma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tatamotors',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tatamotors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tatasteel',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tatasteel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tcs',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tcs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Techm',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'techm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Titan',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'titan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ultracemco',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ultracemco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Upl',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'upl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vedl',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vedl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wipro',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wipro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zeel',
            fields=[
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zeel',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
