# Generated by Django 3.2.10 on 2021-12-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211224_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaniports',
            options={'managed': True, 'verbose_name_plural': 'adaniports'},
        ),
        migrations.AlterModelOptions(
            name='asianpaint',
            options={'verbose_name_plural': 'asianpaint'},
        ),
        migrations.AlterModelOptions(
            name='axisbank',
            options={'managed': True, 'verbose_name_plural': 'axisbank'},
        ),
        migrations.AlterModelOptions(
            name='bajajfinsv',
            options={'managed': True, 'verbose_name_plural': 'bajajfinsv'},
        ),
        migrations.AlterModelOptions(
            name='bajfinance',
            options={'managed': True, 'verbose_name_plural': 'bajfinance'},
        ),
        migrations.AlterModelOptions(
            name='bhartiartl',
            options={'managed': True, 'verbose_name_plural': 'bhartiartl'},
        ),
        migrations.AlterModelOptions(
            name='bpcl',
            options={'managed': True, 'verbose_name_plural': 'bpcl'},
        ),
        migrations.AlterModelOptions(
            name='britannia',
            options={'managed': True, 'verbose_name_plural': 'britannia'},
        ),
        migrations.AlterModelOptions(
            name='cipla',
            options={'managed': True, 'verbose_name_plural': 'cipla'},
        ),
        migrations.AlterModelOptions(
            name='coalindia',
            options={'managed': True, 'verbose_name_plural': 'coalindia'},
        ),
        migrations.AlterModelOptions(
            name='drreddy',
            options={'managed': True, 'verbose_name_plural': 'drreddy'},
        ),
        migrations.AlterModelOptions(
            name='eichermot',
            options={'managed': True, 'verbose_name_plural': 'eichermot'},
        ),
        migrations.AlterModelOptions(
            name='gail',
            options={'managed': True, 'verbose_name_plural': 'gail'},
        ),
        migrations.AlterModelOptions(
            name='grasim',
            options={'managed': True, 'verbose_name_plural': 'grasim'},
        ),
        migrations.AlterModelOptions(
            name='hcltech',
            options={'managed': True, 'verbose_name_plural': 'hcltech'},
        ),
        migrations.AlterModelOptions(
            name='hdfc',
            options={'managed': True, 'verbose_name_plural': 'hdfc'},
        ),
        migrations.AlterModelOptions(
            name='hdfcbank',
            options={'managed': True, 'verbose_name_plural': 'hdfcbank'},
        ),
        migrations.AlterModelOptions(
            name='heromotoco',
            options={'managed': True, 'verbose_name_plural': 'heromotoco'},
        ),
        migrations.AlterModelOptions(
            name='hindalco',
            options={'managed': True, 'verbose_name_plural': 'hindalco'},
        ),
        migrations.AlterModelOptions(
            name='hindunilvr',
            options={'managed': True, 'verbose_name_plural': 'hindunilvr'},
        ),
        migrations.AlterModelOptions(
            name='icicibank',
            options={'managed': True, 'verbose_name_plural': 'icicibank'},
        ),
        migrations.AlterModelOptions(
            name='indusindbk',
            options={'managed': True, 'verbose_name_plural': 'indusindbk'},
        ),
        migrations.AlterModelOptions(
            name='infratel',
            options={'managed': True, 'verbose_name_plural': 'infratel'},
        ),
        migrations.AlterModelOptions(
            name='infy',
            options={'managed': True, 'verbose_name_plural': 'infy'},
        ),
        migrations.AlterModelOptions(
            name='ioc',
            options={'managed': True, 'verbose_name_plural': 'ioc'},
        ),
        migrations.AlterModelOptions(
            name='itc',
            options={'managed': True, 'verbose_name_plural': 'itc'},
        ),
        migrations.AlterModelOptions(
            name='jswsteel',
            options={'managed': True, 'verbose_name_plural': 'jswsteel'},
        ),
        migrations.AlterModelOptions(
            name='kotakbank',
            options={'managed': True, 'verbose_name_plural': 'kotakbank'},
        ),
        migrations.AlterModelOptions(
            name='lt',
            options={'managed': True, 'verbose_name_plural': 'lt'},
        ),
        migrations.AlterModelOptions(
            name='maruti',
            options={'managed': True, 'verbose_name_plural': 'maruti'},
        ),
        migrations.AlterModelOptions(
            name='mm',
            options={'managed': True, 'verbose_name_plural': 'm&m'},
        ),
        migrations.AlterModelOptions(
            name='nestleind',
            options={'managed': True, 'verbose_name_plural': 'nestleind'},
        ),
        migrations.AlterModelOptions(
            name='ntpc',
            options={'managed': True, 'verbose_name_plural': 'ntpc'},
        ),
        migrations.AlterModelOptions(
            name='ongc',
            options={'managed': True, 'verbose_name_plural': 'ongc'},
        ),
        migrations.AlterModelOptions(
            name='powergrid',
            options={'managed': True, 'verbose_name_plural': 'powergrid'},
        ),
        migrations.AlterModelOptions(
            name='reliance',
            options={'managed': True, 'verbose_name_plural': 'reliance'},
        ),
        migrations.AlterModelOptions(
            name='sbin',
            options={'managed': True, 'verbose_name_plural': 'sbin'},
        ),
        migrations.AlterModelOptions(
            name='shreecem',
            options={'managed': True, 'verbose_name_plural': 'shreecem'},
        ),
        migrations.AlterModelOptions(
            name='sunpharma',
            options={'managed': True, 'verbose_name_plural': 'sunpharma'},
        ),
        migrations.AlterModelOptions(
            name='tatamotors',
            options={'managed': True, 'verbose_name_plural': 'tatamotors'},
        ),
        migrations.AlterModelOptions(
            name='tatasteel',
            options={'managed': True, 'verbose_name_plural': 'tatasteel'},
        ),
        migrations.AlterModelOptions(
            name='tcs',
            options={'managed': True, 'verbose_name_plural': 'tcs'},
        ),
        migrations.AlterModelOptions(
            name='techm',
            options={'managed': True, 'verbose_name_plural': 'techm'},
        ),
        migrations.AlterModelOptions(
            name='titan',
            options={'managed': True, 'verbose_name_plural': 'titan'},
        ),
        migrations.AlterModelOptions(
            name='ultracemco',
            options={'managed': True, 'verbose_name_plural': 'ultracemco'},
        ),
        migrations.AlterModelOptions(
            name='upl',
            options={'managed': True, 'verbose_name_plural': 'upl'},
        ),
        migrations.AlterModelOptions(
            name='vedl',
            options={'managed': True, 'verbose_name_plural': 'vedl'},
        ),
        migrations.AlterModelOptions(
            name='wipro',
            options={'managed': True, 'verbose_name_plural': 'wipro'},
        ),
        migrations.AlterModelOptions(
            name='zeel',
            options={'managed': True, 'verbose_name_plural': 'zeel'},
        ),
        migrations.AlterModelTable(
            name='adaniports',
            table=None,
        ),
        migrations.AlterModelTable(
            name='asianpaint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='axisbank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bajajfinsv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bajfinance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bhartiartl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpcl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='britannia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cipla',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coalindia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='drreddy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eichermot',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='grasim',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hcltech',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hdfc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hdfcbank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='heromotoco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hindalco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hindunilvr',
            table=None,
        ),
        migrations.AlterModelTable(
            name='icicibank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='indusindbk',
            table=None,
        ),
        migrations.AlterModelTable(
            name='infratel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='infy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ioc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='itc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jswsteel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kotakbank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='maruti',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mm',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nestleind',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ntpc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ongc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='powergrid',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reliance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sbin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shreecem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sunpharma',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tatamotors',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tatasteel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tcs',
            table=None,
        ),
        migrations.AlterModelTable(
            name='techm',
            table=None,
        ),
        migrations.AlterModelTable(
            name='titan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ultracemco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='upl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vedl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wipro',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zeel',
            table=None,
        ),
    ]
